### ISSUE TITLE
Repository does not include license information

### ISSUE THREAD

**Issue by yarwelp** [lonkamikaze/powerdxx#1]
Please add a LICENSE file with appropriate contents to the root of this repository.

**Comment by lonkamikaze** [comment]
Why?

**Comment by lonkamikaze** [comment]
What license do you want?

**Comment by lonkamikaze** [comment]
Added the ISC license with commit 43d3e1233c04f413a1e51f65bf3eb6c368a1391b.

**Comment by yarwelp** [comment]
Excellent choice of license :)
