### ISSUE TITLE
CURRENT: Assertion failed: (min < max && "minimum must be less than maximum")

### ISSUE THREAD

**Issue by davidschlachter** [lonkamikaze/powerdxx#10]
I'm running 13-CURRENT r358022 on a ThinkPad T480. For a few weeks now powerd++ (built from ports) fails to start. System-provided `powerd` runs fine. I get the following output when starting with `rc.d`:

````
# service powerdxx onestart
Starting powerdxx.
Assertion failed: (min < max && "minimum must be less than maximum"), function init, file /usr/ports/sysutils/powerdxx/work/powerdxx-0.4.3/src/powerd++.cpp, line 525.
Abort trap (core dumped)
/usr/local/etc/rc.d/powerdxx: WARNING: failed to start powerdxx
````
And more or less the same error when attempting to start in the foreground:
````
# powerd++ -vf
powerd++: could not determine critical temperature
	temperature throttling: off
Assertion failed: (min < max && "minimum must be less than maximum"), function init, file /usr/ports/sysutils/powerdxx/work/powerdxx-0.4.3/src/powerd++.cpp, line 525.
Abort trap
````
Here's a link to [the core dump](https://schlachter.ca/powerdxx.core.zip).

Please let me know any other details I could include.

**Comment by davidschlachter** [comment]
Possibly related commit: https://svnweb.freebsd.org/base?view=revision&revision=357336

**Comment by lonkamikaze** [comment]
This is in deed related to the hwpstate support. Powerd++ cannot do anything for you any more (manual frequency control via the sysctl interface is no longer possible). I think there are some loader hints to turn this feature off, but unless hwpstate is malfunctioning in some fashion this is probably not desired. All I can do is fail more gracefully or monitor the state in foreground mode.

I'll take a bit of time to fiddle with the usability implications of this.

**Comment by lonkamikaze** [comment]
I have implemented blacklisting of the hwpstate family of cpufreq drivers with commit fbc5de6619a8f215e702aaf3fe619446da8f8fdc.

I will leave this issue open for further discussion and feedback until the next release.

**Comment by lonkamikaze** [comment]
powerd++ 0.4.4 was released.
