### ISSUE TITLE
High CPU usage of powerd++ process

### ISSUE THREAD

**Issue by Peter2121** [lonkamikaze/powerdxx#12]
Installed from package, started as daemon with the command line:
`/usr/local/sbin/powerd++ --min-ac 1600 --poll 2`
on DELL Latitude E6420 under FreeBSD 11.3 and Enlightenment DE.
PC is connected to external power source. All CPU monitoring tools installed on the PC (htop, glances, evisum) are showing 15-20% of CPU usage of powerd++ all the time. It works correctly itself, changing CPU frequency when  the PC in not hardly charged, but CPU usage seems to be excessive.

**Comment by lonkamikaze** [comment]
You're polling at 500 Hz. Maybe be a bit more conservative?

**Comment by Peter2121** [comment]
Perfect, IMHO some additional info in man about --poll option would be useful ;)

**Comment by lonkamikaze** [comment]
That the default is ms is inherited from powerd. Without that legacy I would've rejected values without units.
```
DESCRIPTION
   ARGUMENTS
     ival    A time interval can be given in seconds or milliseconds.
                   s, ms
             An interval without a unit is treated as milliseconds.
   OPTIONS
     -p, --poll ival
             The polling interval that is used to take load samples and update
             the CPU clock (default 0.5s).
```
