### ISSUE TITLE
Support hwpstate_intel on FreeBSD 13+

### ISSUE THREAD

**Issue by NorwegianRockCat** [lonkamikaze/powerdxx#16]
Hello,

On machines that support  the hwpstate_intel driver, powerdxx refuses to start.

```
Starting powerdxx.
powerd++: (EDRIVER) frequency control driver not supported: hwpstate_intel0
/usr/local/etc/rc.d/powerdxx: WARNING: failed to start powerdxx
```
I'm not sure which Intel CPU support this, but at least Skylake CPUs seem to have it.

**Comment by lonkamikaze** [comment]
Duplicate of #15 .
