### ISSUE TITLE
Separate AC and BATTERY Flags for min/max CPU Speed

### ISSUE THREAD

**Issue by vermaden** [lonkamikaze/powerdxx#2]
Hi,

currently powerdxx does the same as powerd about CPU speed which means -m and -M flags.

It would be useful to provide separate flags for AC and for battery work. For example -bm and -bM for CPU speeds on battery and -am and -aM for CPU speed on AC.

If course backward compatibility with powerd can be sustained with keeping the -m and -M flags which will set -bm and -am to -m setting and -bM and -aM to -M setting accordingly.

Regards,
vermaden

**Comment by lonkamikaze** [comment]
I'm not really getting what you want to achieve. Do you want to set different maximum speeds depending on the AC state?

**Comment by Crest** [comment]
Current hardware is most efficient per executed instruction at max. frequency. If you want to save power run the core(s) at full speed for short bursts and quickly return to sleep. The kernel APIs available to powerd++ limit its possibilities.

The optimal idle power efficiency would probably be reached by putting unused cores into the deepest sleep mode available after rerouting interrupts to one active core. Further gains are possible by relaxing the timer precision and using the gained freedom to batch wakeups on remaining core. The FreeBSD kernel doesn't implement either of those optimisations and implementing them would require tight integration between the scheduler, interrupt routing and power management code.

**Comment by vermaden** [comment]
Yes.Od: "Dominic Fandrey" &lt;notifications@github.com&gt;Do: "lonkamikaze/powerdxx" &lt;powerdxx@noreply.github.com&gt;; Wysłane: 12:36 Piątek 2016-08-12Temat: Re: [lonkamikaze/powerdxx] Separate AC and BATTERY Flags for min/max CPU Speed (#2)I'm not really getting what you want to achieve. Do you want to set different maximum speeds depending on the AC state?

**Comment by lonkamikaze** [comment]
Implemented with commit 602cc988b2fea8eb036503877883b351bcf0a19f.

**Comment by vermaden** [comment]
Man, that was fast ;)... and Thank You at the same time.Regards,vermadenOd: "Dominic Fandrey" &lt;notifications@github.com&gt;Do: "lonkamikaze/powerdxx" &lt;powerdxx@noreply.github.com&gt;; Wysłane: 19:34 Piątek 2016-08-12Temat: Re: [lonkamikaze/powerdxx] Separate AC and BATTERY Flags for min/max CPU Speed (#2)Implemented with commit 602cc98.
