### ISSUE TITLE
Rename all files from 'powerd++' to 'powerdxx'

### ISSUE THREAD

**Issue by vermaden** [lonkamikaze/powerdxx#4]
Hi,

please rename all files within your project from 'powerd++' to 'powerdxx' as these '++' are not compatible with a lot of base FreeBSD tools like pgrep for example:

```
# pgrep powerd++ 
pgrep: Cannot compile regular expression `powerd++' (repetition-operator operand invalid)
```

```
# pgrep powerd\+\+
pgrep: Cannot compile regular expression `powerd++' (repetition-operator operand invalid)
```

```
# pgrep 'powerd++'
pgrep: Cannot compile regular expression `powerd++' (repetition-operator operand invalid)
```

Regards.

**Comment by z2v** [comment]
Try double quotes:

```
❯ pgrep "powerd\+\+"
64432
```

**Comment by vermaden** [comment]
Thanks for workaround, but its pointless to have both powerd++ and powerdxx names, especially when package name is 'powerdxx' and some directories are also named with 'xx' instead of '++' like **/usr/local/share/doc/powerdxx**.

**Comment by lonkamikaze** [comment]
I don't think you have a strong argument here, there is a lot of precedence for stuff with + in the name, even some in the base system. I'd say it's kind of a defect of pgrep not to have an -F parameter.

I'm willing to make the change if you can get a couple of people to second your motion.

**Comment by vermaden** [comment]
I will not fight for it, its Your software and Your right to name it the way You want, I just shared my thought.

Regards.

**Comment by lonkamikaze** [comment]
Dropped for lack of interest.
