### ISSUE TITLE
powerd++ fails to start on hyperthreading capable CPUs with hyperthreading disabled

### ISSUE THREAD

**Issue by Crest** [lonkamikaze/powerdxx#7]
If the machdep.hyperthreading_allowed tuneable is set to zero to mitigate TLBleed powerd++ fails to start with ESYSCTL.

**Comment by lonkamikaze** [comment]
I just published 0.4.0-rc1, which should fix this issue.

**Comment by lonkamikaze** [comment]
The 0.4.0 release addresses this.
